#!/usr/bin/env python3
"""
Rule Transpiler — JSON Tax Rules → Deterministic NML Programs

Unlike the XGBoost transpiler (which exports ML-learned thresholds),
this transpiler converts exact tax rules into NML programs.
Every bracket boundary, rate, and cap is encoded precisely as specified.

Usage:
    python3 rule_transpiler.py tax_rules_2024.json
    ./nml tax_rules_calc.nml tax_rules_test.nml.data
"""

import json
import sys


# ═══════════════════════════════════════════
# NML Program Builder with label-based jumps
# ═══════════════════════════════════════════

class NMLProgram:
    """Builds an NML program with automatic jump offset resolution."""

    def __init__(self):
        self.entries = []
        self.labels = {}
        self._instr_count = 0

    def comment(self, text):
        self.entries.append({"type": "comment", "text": f"; {text}"})

    def blank(self):
        self.entries.append({"type": "comment", "text": ""})

    def instr(self, text):
        self.entries.append({"type": "instr", "text": text, "idx": self._instr_count})
        self._instr_count += 1

    def jump(self, opcode, label):
        self.entries.append({
            "type": "instr", "text": opcode, "idx": self._instr_count,
            "fixup": label
        })
        self._instr_count += 1

    def label(self, name):
        if name in self.labels:
            raise ValueError(f"Duplicate label: {name}")
        self.labels[name] = self._instr_count

    def build(self):
        lines = []
        for e in self.entries:
            if e["type"] == "comment":
                lines.append(e["text"])
            elif "fixup" in e:
                target = self.labels[e["fixup"]]
                offset = target - e["idx"] - 1
                lines.append(f"{e['text']}  #{offset}")
            else:
                lines.append(e["text"])
        return "\n".join(lines)

    @property
    def instruction_count(self):
        return self._instr_count


# ═══════════════════════════════════════════
# Tax Rule Transpiler
# ═══════════════════════════════════════════

class TaxRuleTranspiler:
    """
    Converts JSON tax rules into a deterministic NML program.

    Register allocation:
        R0  gross_pay (kept throughout)
        R1  filing_status (used for branching)
        R2  dependents (used for credits)
        R3  scratch (reused after AGI computation)
        R4  scratch (reused after AGI computation)
        R5  state_code (used for state tax branching)
        R6  pay_periods_inv (1/pay_periods, for final division)
        R7  taxable_income (computed, kept through brackets)
        R8  scratch
        R9  state_tax result / scratch
        RA  federal_tax accumulator
        RB  FICA accumulator
        RC  scratch for LEAF/TACC
    """

    def __init__(self, rules):
        self.rules = rules
        self.p = NMLProgram()

    def transpile(self):
        p = self.p

        p.comment("═══════════════════════════════════════════")
        p.comment(f" {self.rules['name']}")
        p.comment(" Deterministic — transpiled from JSON rules")
        p.comment(f" Generated by rule_transpiler.py")
        p.comment("═══════════════════════════════════════════")
        p.blank()

        self._emit_load_inputs()
        self._emit_compute_agi()
        self._emit_standard_deduction()
        self._emit_floor_register("R7", "taxable_nonneg")
        self._emit_federal_brackets()
        self._emit_fica()
        self._emit_state_tax()
        self._emit_totals()

        nml = p.build()
        instr_count = p.instruction_count
        p.comment("")
        p.comment(f" {instr_count} instructions")
        return p.build()

    # ─── Phase 1: Load inputs ───

    def _emit_load_inputs(self):
        p = self.p
        p.comment("─── Load inputs ───")
        p.instr("LD    R0 @gross_pay")
        p.instr("LD    R1 @filing_status")
        p.instr("LD    R2 @dependents")
        p.instr("LD    R3 @pre_tax_deduct_pct")
        p.instr("LD    R4 @retirement_pct")
        p.instr("LD    R5 @state_code")
        p.instr("LD    R6 @pay_periods_inv")
        p.blank()

    # ─── Phase 2: Compute adjusted gross income ───

    def _emit_compute_agi(self):
        p = self.p
        p.comment("─── Compute taxable income ───")
        p.comment("R7 = gross * (1 - pre_tax_pct) - gross * retirement_pct - std_deduction")
        p.instr("EMUL  R8 R0 R3")          # R8 = gross * pre_tax_pct
        p.instr("MSUB  R7 R0 R8")          # R7 = gross - pre_tax_deductions
        p.instr("EMUL  R8 R0 R4")          # R8 = gross * retirement_pct
        p.instr("MSUB  R7 R7 R8")          # R7 = adjusted gross income
        p.blank()

    # ─── Phase 3: Standard deduction ───

    def _emit_standard_deduction(self):
        p = self.p
        deductions = self.rules["standard_deduction"]
        statuses = sorted(deductions.keys(), key=int)

        p.comment("─── Standard deduction (by filing status) ───")

        for i, status in enumerate(statuses):
            amt = deductions[status]
            is_last = (i == len(statuses) - 1)

            if not is_last:
                threshold = int(status) + 0.5
                p.instr(f"CMPF  RE R1 #0 #{threshold:.1f}")
                p.jump("JMPF", f"deduct_not_{status}")
                p.instr(f"LEAF  R8 #{amt:.2f}")
                p.jump("JUMP", "apply_deduction")
                p.label(f"deduct_not_{status}")
            else:
                p.instr(f"LEAF  R8 #{amt:.2f}")

        p.label("apply_deduction")
        p.instr("MSUB  R7 R7 R8")
        p.blank()

    # ─── Floor a register at 0 ───

    def _emit_floor_register(self, reg, label_suffix):
        p = self.p
        p.comment(f"─── Floor {reg} at zero ───")
        p.instr(f"CMPF  RE {reg} #0 #0.0")
        p.jump("JMPF", f"{label_suffix}_ok")
        p.instr(f"ALLC  {reg} #[1]")
        p.label(f"{label_suffix}_ok")
        p.blank()

    # ─── Phase 4: Federal progressive brackets ───

    def _emit_federal_brackets(self):
        p = self.p
        all_brackets = self.rules["federal_brackets"]
        statuses = sorted(all_brackets.keys(), key=int)

        p.comment("─── Federal income tax (progressive brackets) ───")
        p.instr("ALLC  RA #[1]")

        for i, status in enumerate(statuses):
            is_last_status = (i == len(statuses) - 1)
            brackets = all_brackets[status]

            if not is_last_status:
                threshold = int(status) + 0.5
                p.instr(f"CMPF  RE R1 #0 #{threshold:.1f}")
                p.jump("JMPF", f"fed_not_{status}")

            self._emit_one_bracket_table(brackets, f"s{status}")

            if not is_last_status:
                p.jump("JUMP", "done_federal")
                p.label(f"fed_not_{status}")

        p.label("done_federal")
        p.blank()

    def _emit_one_bracket_table(self, brackets, prefix):
        p = self.p

        for j, bracket in enumerate(brackets):
            floor_val, ceil_val, rate = bracket
            is_last = (j == len(brackets) - 1)

            if not is_last:
                p.instr(f"CMPF  RE R7 #0 #{ceil_val:.2f}")
                p.jump("JMPT", f"{prefix}_partial_{j}")

                full_tax = (ceil_val - floor_val) * rate
                p.instr(f"LEAF  RC #{full_tax:.2f}")
                p.instr("TACC  RA RA RC")
                p.jump("JUMP", f"{prefix}_next_{j + 1}")

                p.label(f"{prefix}_partial_{j}")
                if floor_val == 0:
                    p.instr(f"SCLR  R8 R7 #{rate:.4f}")
                else:
                    p.instr(f"LEAF  RC #{floor_val:.2f}")
                    p.instr("MSUB  R8 R7 RC")
                    p.instr(f"SCLR  R8 R8 #{rate:.4f}")
                p.instr("TACC  RA RA R8")
                p.jump("JUMP", "done_federal")

                p.label(f"{prefix}_next_{j + 1}")
            else:
                if floor_val == 0:
                    p.instr(f"SCLR  R8 R7 #{rate:.4f}")
                else:
                    p.instr(f"LEAF  RC #{floor_val:.2f}")
                    p.instr("MSUB  R8 R7 RC")
                    p.instr(f"SCLR  R8 R8 #{rate:.4f}")
                p.instr("TACC  RA RA R8")

    # ─── Phase 5: FICA ───

    def _emit_fica(self):
        p = self.p
        fica = self.rules["fica"]
        ss = fica["social_security"]
        med = fica["medicare"]

        p.comment("─── FICA taxes ───")
        p.instr("ALLC  RB #[1]")

        p.comment(f"Social Security: {ss['rate']*100:.1f}% on first ${ss['wage_base']:,.0f}")
        p.instr(f"CMPF  RE R0 #0 #{ss['wage_base']:.2f}")
        p.jump("JMPT", "ss_under_cap")
        ss_max_tax = ss["wage_base"] * ss["rate"]
        p.instr(f"LEAF  RC #{ss_max_tax:.2f}")
        p.instr("TACC  RB RB RC")
        p.jump("JUMP", "ss_done")
        p.label("ss_under_cap")
        p.instr(f"SCLR  RC R0 #{ss['rate']:.4f}")
        p.instr("TACC  RB RB RC")
        p.label("ss_done")

        p.comment(f"Medicare: {med['rate']*100:.2f}% on all earnings")
        p.instr(f"SCLR  RC R0 #{med['rate']:.4f}")
        p.instr("TACC  RB RB RC")

        if "additional_medicare" in fica:
            am = fica["additional_medicare"]
            p.comment(f"Additional Medicare: {am['rate']*100:.1f}% over ${am['threshold']:,.0f}")
            p.instr(f"CMPF  RE R0 #0 #{am['threshold']:.2f}")
            p.jump("JMPT", "no_addl_med")
            p.instr(f"LEAF  RC #{am['threshold']:.2f}")
            p.instr("MSUB  R8 R0 RC")
            p.instr(f"SCLR  R8 R8 #{am['rate']:.4f}")
            p.instr("TACC  RB RB R8")
            p.label("no_addl_med")

        p.blank()

    # ─── Phase 6: State income tax ───

    def _emit_state_tax(self):
        p = self.p
        rates = self.rules["state_tax"]
        all_codes = sorted(rates.keys(), key=int)

        p.comment("─── State income tax ───")
        p.instr("ALLC  R9 #[1]")

        nonzero = [(k, rates[k]) for k in all_codes if rates[k] > 0]
        if not nonzero:
            p.label("done_state")
            p.blank()
            return

        # Skip past all state tax if code has zero rate
        zero_codes = [k for k in all_codes if rates[k] == 0]
        for zc in zero_codes:
            threshold = int(zc) + 0.5
            p.instr(f"CMPF  RE R5 #0 #{threshold:.1f}")
            p.jump("JMPT", "done_state")

        for i, (code, rate) in enumerate(nonzero):
            is_last = (i == len(nonzero) - 1)
            threshold = int(code) + 0.5

            if not is_last:
                p.instr(f"CMPF  RE R5 #0 #{threshold:.1f}")
                p.jump("JMPF", f"state_not_{code}")
                p.instr(f"SCLR  R9 R7 #{rate:.4f}")
                p.jump("JUMP", "done_state")
                p.label(f"state_not_{code}")
            else:
                p.instr(f"SCLR  R9 R7 #{rate:.4f}")

        p.label("done_state")
        p.blank()

    # ─── Phase 7: Totals ───

    def _emit_totals(self):
        p = self.p
        credit = self.rules["credits"]["dependent"]

        p.comment("─── Total tax and net pay ───")
        p.instr("TACC  R8 RA RB")              # R8 = federal + FICA
        p.instr("TACC  R8 R8 R9")              # R8 += state tax
        p.instr(f"SCLR  R3 R2 #{credit:.2f}")  # R3 = dependents * credit
        p.instr("MSUB  R8 R8 R3")              # R8 = total tax - credits
        self._emit_floor_register("R8", "total_tax_nonneg")

        p.comment("─── Store intermediate results before overwrite ───")
        p.instr("ST    R9 @state_tax")
        p.instr("ST    R7 @taxable_income")
        p.instr("ST    RA @federal_tax")
        p.instr("ST    RB @fica_tax")
        p.instr("ST    R8 @total_tax")

        p.comment("─── Net pay per period ───")
        p.instr("MSUB  R9 R0 R8")              # R9 = gross - total_tax (annual)
        p.instr("EMUL  R9 R9 R6")              # R9 *= 1/pay_periods

        p.instr("ST    R9 @net_pay")
        p.instr("HALT")


# ═══════════════════════════════════════════
# Data file generator
# ═══════════════════════════════════════════

def generate_data_file(employee, pay_periods):
    """Generate an .nml.data file for an employee."""
    lines = [
        "# NML Tax Rules Calculator — Employee Data",
        f"@gross_pay shape=1 data={employee['gross_pay']:.2f}",
        f"@filing_status shape=1 data={employee['filing_status']:.1f}",
        f"@dependents shape=1 data={employee['dependents']:.1f}",
        f"@pre_tax_deduct_pct shape=1 data={employee['pre_tax_deduct_pct']:.4f}",
        f"@retirement_pct shape=1 data={employee['retirement_pct']:.4f}",
        f"@state_code shape=1 data={employee['state_code']:.1f}",
        f"@pay_periods_inv shape=1 data={1.0 / pay_periods:.8f}",
    ]
    return "\n".join(lines)


# ═══════════════════════════════════════════
# Analytical tax calculator (for validation)
# ═══════════════════════════════════════════

def compute_tax_analytical(employee, pay_periods, rules):
    """Compute expected tax results analytically for validation."""
    gross = employee["gross_pay"]
    fs = str(int(employee["filing_status"]))
    deps = employee["dependents"]
    pre_tax = employee["pre_tax_deduct_pct"]
    retire = employee["retirement_pct"]
    sc = str(int(employee["state_code"]))

    agi = gross * (1 - pre_tax) - gross * retire
    std_ded = rules["standard_deduction"].get(fs, 14600)
    taxable = max(0, agi - std_ded)

    brackets = rules["federal_brackets"][fs]
    federal = 0.0
    for floor_val, ceil_val, rate in brackets:
        if ceil_val is None:
            federal += (taxable - floor_val) * rate
            break
        if taxable <= floor_val:
            break
        if taxable >= ceil_val:
            federal += (ceil_val - floor_val) * rate
        else:
            federal += (taxable - floor_val) * rate
            break

    ss = rules["fica"]["social_security"]
    ss_tax = min(gross, ss["wage_base"]) * ss["rate"]
    med = rules["fica"]["medicare"]
    med_tax = gross * med["rate"]
    addl = rules["fica"].get("additional_medicare", {})
    addl_tax = max(0, gross - addl.get("threshold", 1e18)) * addl.get("rate", 0)
    fica = ss_tax + med_tax + addl_tax

    state_rate = rules["state_tax"].get(sc, 0.0)
    state = taxable * state_rate

    credit = deps * rules["credits"]["dependent"]
    total_tax = max(0, federal + fica + state - credit)
    net_annual = gross - total_tax
    net_per_period = net_annual / pay_periods

    return {
        "taxable_income": taxable,
        "federal_tax": federal,
        "fica_tax": fica,
        "state_tax": state,
        "total_tax": total_tax,
        "net_pay": net_per_period,
    }


# ═══════════════════════════════════════════
# Main
# ═══════════════════════════════════════════

TEST_EMPLOYEES = [
    {
        "name": "Junior Developer (Single, no deps, TX)",
        "data": {"gross_pay": 65000, "filing_status": 0, "dependents": 0,
                 "pre_tax_deduct_pct": 0.03, "retirement_pct": 0.06,
                 "state_code": 0},
        "pay_periods": 26,
    },
    {
        "name": "Senior Manager (Married, 2 kids, CA)",
        "data": {"gross_pay": 185000, "filing_status": 1, "dependents": 2,
                 "pre_tax_deduct_pct": 0.08, "retirement_pct": 0.12,
                 "state_code": 3},
        "pay_periods": 24,
    },
    {
        "name": "Executive (Single, 0 deps, NY)",
        "data": {"gross_pay": 350000, "filing_status": 0, "dependents": 0,
                 "pre_tax_deduct_pct": 0.05, "retirement_pct": 0.15,
                 "state_code": 3},
        "pay_periods": 24,
    },
    {
        "name": "Part-time Worker (HoH, 3 deps, FL)",
        "data": {"gross_pay": 28000, "filing_status": 3, "dependents": 3,
                 "pre_tax_deduct_pct": 0.0, "retirement_pct": 0.0,
                 "state_code": 0},
        "pay_periods": 52,
    },
]


def main():
    rules_path = sys.argv[1] if len(sys.argv) > 1 else "tax_rules_2024.json"

    with open(rules_path) as f:
        rules = json.load(f)

    print("=" * 64)
    print(f"  Rule Transpiler — {rules['name']}")
    print("=" * 64)
    print()

    # Transpile
    transpiler = TaxRuleTranspiler(rules)
    nml_program = transpiler.transpile()

    instr_count = transpiler.p.instruction_count
    print(f"  [1/3] Transpiled: {instr_count} NML instructions")

    nml_path = "tax_rules_calc.nml"
    with open(nml_path, "w") as f:
        f.write(nml_program)
    print(f"         Wrote: {nml_path}")
    print()

    # Generate test data files and compute expected results
    print(f"  [2/3] Analytical validation:")
    print()
    print(f"  {'Employee':<45} {'Net/Period':>12} {'Fed Tax':>12} {'FICA':>12}")
    print(f"  {'-'*45} {'-'*12} {'-'*12} {'-'*12}")

    for emp in TEST_EMPLOYEES:
        result = compute_tax_analytical(emp["data"], emp["pay_periods"], rules)
        print(f"  {emp['name']:<45} "
              f"${result['net_pay']:>10,.2f} "
              f"${result['federal_tax']:>10,.2f} "
              f"${result['fica_tax']:>10,.2f}")

    # Write test data file for the last employee tested
    for emp in TEST_EMPLOYEES:
        data_file = generate_data_file(emp["data"], emp["pay_periods"])
        fname = "tax_rules_test.nml.data"
        with open(fname, "w") as f:
            f.write(data_file)

    print()
    print(f"  [3/3] Files generated:")
    print(f"         {nml_path:<30} — Deterministic NML program")
    print(f"         tax_rules_test.nml.data       — Test employee data")
    print()
    print(f"  Run:")
    print(f"    ./nml {nml_path} tax_rules_test.nml.data")
    print()


if __name__ == "__main__":
    main()
